name: First Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  check_first_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if first PR
        id: check_first_pr
        uses: peter-evans/is-first-pr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on first PR
        if: steps.check_first_pr.outputs.first_pr == 'true'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Congratulations on your first pull request! 🎉'
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
